name = "RetrospectiveMotionCorrectionMRI"
uuid = "24772341-69a6-4cfa-a9d8-04aed0acc5f5"
authors = ["Gabrio Rizzuti <rizzuti.gabrio@gmail.com>"]
version = "1.0.0"

[deps]
AbstractLinearOperators = "bb902dec-a34b-4f3c-9707-4856bea60ee0"
AbstractProximableFunctions = "9ed10759-246d-4065-822b-90d32585fe69"
FastSolversForWeightedTV = "3521e485-16e8-49c3-934a-dec609b578e8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
UtilitiesForMRI = "5f442635-cb9d-4e13-b358-1c870cfef0cf"

[compat]
julia = "1.8"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
